# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-IU6yxsTT8DALeYjAUflDJ6TlG1FrLrU
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

df = pd.read_csv("/content/Bank Customer Churn Prediction.csv")

df.head()

df.info()

df.describe()

df.isnull().sum()

plt.figure(figsize=(6,4))

sns.countplot(x='churn', data=df)

plt.title("Customer Churn Distribution")
plt.savefig("class_distribution.png")
plt.show()

df1=df.copy()

le=LabelEncoder()

df1["country"]=le.fit_transform(df1["country"])
df1["gender"]=le.fit_transform(df1["gender"])

plt.figure(figsize=(10,8))

sns.heatmap(df1.corr(),annot=True,cmap="coolwarm")

plt.title("Correlation Heatmap")
plt.savefig("correlation_heatmap.png")

plt.show()

df.drop("customer_id",axis=1,inplace=True)

le=LabelEncoder()

df["country"]=le.fit_transform(df["country"])
df["gender"]=le.fit_transform(df["gender"])

X=df.drop("churn",axis=1)

y=df["churn"]

X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

sc=StandardScaler()

X_train=sc.fit_transform(X_train)

X_test=sc.transform(X_test)

model=RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

acc=accuracy_score(y_test,y_pred)

print("Accuracy :",acc)

print(classification_report(y_test,y_pred))

cm=confusion_matrix(y_test,y_pred)

plt.figure(figsize=(6,5))

sns.heatmap(cm,
            annot=True,
            fmt="d",
            cmap="Blues")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.savefig("confusion_matrix.png")

plt.show()

importance=pd.DataFrame({
    "Feature":X.columns,
    "Importance":model.feature_importances_
})

importance=importance.sort_values(
    by="Importance",
    ascending=False
)

plt.figure(figsize=(8,6))

sns.barplot(
    x="Importance",
    y="Feature",
    data=importance
)

plt.title("Feature Importance")

plt.savefig("feature_importance.png")

plt.show()

plt.figure(figsize=(7,5))

sns.histplot(df["age"],bins=20,kde=True)

plt.title("Age Distribution")

plt.savefig("age_distribution.png")

plt.show()

plt.figure(figsize=(7,5))

sns.histplot(df["balance"],bins=30,kde=True)

plt.title("Balance Distribution")

plt.savefig("balance_distribution.png")

plt.show()